---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```
# arc.heatplot 

R package for creating Heatplots for the Arcproject's water quality data.

## Installation

```{r installation, eval = FALSE}
library(devtools)
install_github("ucd-cws/wq-heatplot")
```


## Basic Use

### Load Data

Export all the water quality data from a given slough using the [arcproject-wq-processing toolbox](https://github.com/ucd-cws/arcproject-wq-processing) `Export Heatplot data CSV` tool.

```{r}
# load data from the csv
data <- read.csv("tests/example_data.csv", stringsAsFactors = FALSE)

# view first 5 rows
head(data, 5)

```

### Default Heatplot

```{r}
library(arc.heatplot)

p <- heatplot(data, dateField = "date_time", distanceField = "m_value", wqVariable = "temp", title="Water Temperature")

plot(p)

```

### Change Color Ramp

```{r,message=FALSE, warning=FALSE}

p2 <- p + change_gradient_breaks(c("blue", "orange", "red"), c(0, 5, 25)) # uses 3 colors with breaks at 0, 5 & 25

plot(p2)

```


### Modify plot appearance

```{r,message=FALSE, warning=FALSE}

# modify the plot object using standard ggplot2 operations

# remove legend
p3 <- p + guides(fill=FALSE) # no legend

# add lines for the xy axis
p4 <- p3 + theme(axis.line = element_line(color="black", size = 1))

p4

```

### Full Example - custom color scale for salinity for 2016

```{r,message=FALSE, warning=FALSE}

# subset data to only include dates in 2016
data_sub_2016 <- subset(data, date_time > "2016-01-01" & date_time < "2017-01-01")

# generate basic heatplot for salinity
p <- heatplot(data_sub_2016, dateField = "date_time", distanceField = "m_value", wqVariable = "salinity", title="Salinity - 2016 Only")

plot(p)

# find the min/max of salinity to use as the endpoints of the color ramp
min_sal <- min(data_sub_2016$salinity)
max_sal <- max(data_sub_2016$salinity)

print(paste("Range of Salinity:", min_sal, "-", max_sal))

# change the break values for the color ramp but keep the default colors
p2 <- p + change_gradient_breaks(mapped_break_values = c(min_sal, 0.1, 0.2, 0.3, max_sal)) + ggtitle("Salinity - 2016 only + modified color scale")


plot(p2)

```
